// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package humidity;

public final class Temp {
  private Temp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CurrentHumidityRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:humidity.CurrentHumidityRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string zone_id = 1;</code>
     */
    java.lang.String getZoneId();
    /**
     * <code>string zone_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getZoneIdBytes();
  }
  /**
   * Protobuf type {@code humidity.CurrentHumidityRequest}
   */
  public  static final class CurrentHumidityRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:humidity.CurrentHumidityRequest)
      CurrentHumidityRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrentHumidityRequest.newBuilder() to construct.
    private CurrentHumidityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrentHumidityRequest() {
      zoneId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CurrentHumidityRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              zoneId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return humidity.Temp.internal_static_humidity_CurrentHumidityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return humidity.Temp.internal_static_humidity_CurrentHumidityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              humidity.Temp.CurrentHumidityRequest.class, humidity.Temp.CurrentHumidityRequest.Builder.class);
    }

    public static final int ZONE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object zoneId_;
    /**
     * <code>string zone_id = 1;</code>
     */
    public java.lang.String getZoneId() {
      java.lang.Object ref = zoneId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zoneId_ = s;
        return s;
      }
    }
    /**
     * <code>string zone_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getZoneIdBytes() {
      java.lang.Object ref = zoneId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getZoneIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, zoneId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getZoneIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, zoneId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof humidity.Temp.CurrentHumidityRequest)) {
        return super.equals(obj);
      }
      humidity.Temp.CurrentHumidityRequest other = (humidity.Temp.CurrentHumidityRequest) obj;

      boolean result = true;
      result = result && getZoneId()
          .equals(other.getZoneId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ZONE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getZoneId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static humidity.Temp.CurrentHumidityRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.CurrentHumidityRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(humidity.Temp.CurrentHumidityRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code humidity.CurrentHumidityRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:humidity.CurrentHumidityRequest)
        humidity.Temp.CurrentHumidityRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return humidity.Temp.internal_static_humidity_CurrentHumidityRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return humidity.Temp.internal_static_humidity_CurrentHumidityRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                humidity.Temp.CurrentHumidityRequest.class, humidity.Temp.CurrentHumidityRequest.Builder.class);
      }

      // Construct using humidity.Temp.CurrentHumidityRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        zoneId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return humidity.Temp.internal_static_humidity_CurrentHumidityRequest_descriptor;
      }

      @java.lang.Override
      public humidity.Temp.CurrentHumidityRequest getDefaultInstanceForType() {
        return humidity.Temp.CurrentHumidityRequest.getDefaultInstance();
      }

      @java.lang.Override
      public humidity.Temp.CurrentHumidityRequest build() {
        humidity.Temp.CurrentHumidityRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public humidity.Temp.CurrentHumidityRequest buildPartial() {
        humidity.Temp.CurrentHumidityRequest result = new humidity.Temp.CurrentHumidityRequest(this);
        result.zoneId_ = zoneId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof humidity.Temp.CurrentHumidityRequest) {
          return mergeFrom((humidity.Temp.CurrentHumidityRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(humidity.Temp.CurrentHumidityRequest other) {
        if (other == humidity.Temp.CurrentHumidityRequest.getDefaultInstance()) return this;
        if (!other.getZoneId().isEmpty()) {
          zoneId_ = other.zoneId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        humidity.Temp.CurrentHumidityRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (humidity.Temp.CurrentHumidityRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object zoneId_ = "";
      /**
       * <code>string zone_id = 1;</code>
       */
      public java.lang.String getZoneId() {
        java.lang.Object ref = zoneId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zoneId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getZoneIdBytes() {
        java.lang.Object ref = zoneId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zoneId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public Builder setZoneId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public Builder clearZoneId() {
        
        zoneId_ = getDefaultInstance().getZoneId();
        onChanged();
        return this;
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public Builder setZoneIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zoneId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:humidity.CurrentHumidityRequest)
    }

    // @@protoc_insertion_point(class_scope:humidity.CurrentHumidityRequest)
    private static final humidity.Temp.CurrentHumidityRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new humidity.Temp.CurrentHumidityRequest();
    }

    public static humidity.Temp.CurrentHumidityRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrentHumidityRequest>
        PARSER = new com.google.protobuf.AbstractParser<CurrentHumidityRequest>() {
      @java.lang.Override
      public CurrentHumidityRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrentHumidityRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CurrentHumidityRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CurrentHumidityRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public humidity.Temp.CurrentHumidityRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CurrentHumidityResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:humidity.CurrentHumidityResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float current_humidity = 1;</code>
     */
    float getCurrentHumidity();
  }
  /**
   * Protobuf type {@code humidity.CurrentHumidityResponse}
   */
  public  static final class CurrentHumidityResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:humidity.CurrentHumidityResponse)
      CurrentHumidityResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrentHumidityResponse.newBuilder() to construct.
    private CurrentHumidityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrentHumidityResponse() {
      currentHumidity_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CurrentHumidityResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              currentHumidity_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return humidity.Temp.internal_static_humidity_CurrentHumidityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return humidity.Temp.internal_static_humidity_CurrentHumidityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              humidity.Temp.CurrentHumidityResponse.class, humidity.Temp.CurrentHumidityResponse.Builder.class);
    }

    public static final int CURRENT_HUMIDITY_FIELD_NUMBER = 1;
    private float currentHumidity_;
    /**
     * <code>float current_humidity = 1;</code>
     */
    public float getCurrentHumidity() {
      return currentHumidity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currentHumidity_ != 0F) {
        output.writeFloat(1, currentHumidity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currentHumidity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, currentHumidity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof humidity.Temp.CurrentHumidityResponse)) {
        return super.equals(obj);
      }
      humidity.Temp.CurrentHumidityResponse other = (humidity.Temp.CurrentHumidityResponse) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getCurrentHumidity())
          == java.lang.Float.floatToIntBits(
              other.getCurrentHumidity()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENT_HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCurrentHumidity());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static humidity.Temp.CurrentHumidityResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.CurrentHumidityResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(humidity.Temp.CurrentHumidityResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code humidity.CurrentHumidityResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:humidity.CurrentHumidityResponse)
        humidity.Temp.CurrentHumidityResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return humidity.Temp.internal_static_humidity_CurrentHumidityResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return humidity.Temp.internal_static_humidity_CurrentHumidityResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                humidity.Temp.CurrentHumidityResponse.class, humidity.Temp.CurrentHumidityResponse.Builder.class);
      }

      // Construct using humidity.Temp.CurrentHumidityResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currentHumidity_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return humidity.Temp.internal_static_humidity_CurrentHumidityResponse_descriptor;
      }

      @java.lang.Override
      public humidity.Temp.CurrentHumidityResponse getDefaultInstanceForType() {
        return humidity.Temp.CurrentHumidityResponse.getDefaultInstance();
      }

      @java.lang.Override
      public humidity.Temp.CurrentHumidityResponse build() {
        humidity.Temp.CurrentHumidityResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public humidity.Temp.CurrentHumidityResponse buildPartial() {
        humidity.Temp.CurrentHumidityResponse result = new humidity.Temp.CurrentHumidityResponse(this);
        result.currentHumidity_ = currentHumidity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof humidity.Temp.CurrentHumidityResponse) {
          return mergeFrom((humidity.Temp.CurrentHumidityResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(humidity.Temp.CurrentHumidityResponse other) {
        if (other == humidity.Temp.CurrentHumidityResponse.getDefaultInstance()) return this;
        if (other.getCurrentHumidity() != 0F) {
          setCurrentHumidity(other.getCurrentHumidity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        humidity.Temp.CurrentHumidityResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (humidity.Temp.CurrentHumidityResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float currentHumidity_ ;
      /**
       * <code>float current_humidity = 1;</code>
       */
      public float getCurrentHumidity() {
        return currentHumidity_;
      }
      /**
       * <code>float current_humidity = 1;</code>
       */
      public Builder setCurrentHumidity(float value) {
        
        currentHumidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float current_humidity = 1;</code>
       */
      public Builder clearCurrentHumidity() {
        
        currentHumidity_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:humidity.CurrentHumidityResponse)
    }

    // @@protoc_insertion_point(class_scope:humidity.CurrentHumidityResponse)
    private static final humidity.Temp.CurrentHumidityResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new humidity.Temp.CurrentHumidityResponse();
    }

    public static humidity.Temp.CurrentHumidityResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrentHumidityResponse>
        PARSER = new com.google.protobuf.AbstractParser<CurrentHumidityResponse>() {
      @java.lang.Override
      public CurrentHumidityResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrentHumidityResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CurrentHumidityResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CurrentHumidityResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public humidity.Temp.CurrentHumidityResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdjustHumidityRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:humidity.AdjustHumidityRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string zone_id = 1;</code>
     */
    java.lang.String getZoneId();
    /**
     * <code>string zone_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getZoneIdBytes();

    /**
     * <code>float humidity_adjustment = 2;</code>
     */
    float getHumidityAdjustment();
  }
  /**
   * Protobuf type {@code humidity.AdjustHumidityRequest}
   */
  public  static final class AdjustHumidityRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:humidity.AdjustHumidityRequest)
      AdjustHumidityRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdjustHumidityRequest.newBuilder() to construct.
    private AdjustHumidityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdjustHumidityRequest() {
      zoneId_ = "";
      humidityAdjustment_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdjustHumidityRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              zoneId_ = s;
              break;
            }
            case 21: {

              humidityAdjustment_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return humidity.Temp.internal_static_humidity_AdjustHumidityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return humidity.Temp.internal_static_humidity_AdjustHumidityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              humidity.Temp.AdjustHumidityRequest.class, humidity.Temp.AdjustHumidityRequest.Builder.class);
    }

    public static final int ZONE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object zoneId_;
    /**
     * <code>string zone_id = 1;</code>
     */
    public java.lang.String getZoneId() {
      java.lang.Object ref = zoneId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zoneId_ = s;
        return s;
      }
    }
    /**
     * <code>string zone_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getZoneIdBytes() {
      java.lang.Object ref = zoneId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HUMIDITY_ADJUSTMENT_FIELD_NUMBER = 2;
    private float humidityAdjustment_;
    /**
     * <code>float humidity_adjustment = 2;</code>
     */
    public float getHumidityAdjustment() {
      return humidityAdjustment_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getZoneIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, zoneId_);
      }
      if (humidityAdjustment_ != 0F) {
        output.writeFloat(2, humidityAdjustment_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getZoneIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, zoneId_);
      }
      if (humidityAdjustment_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, humidityAdjustment_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof humidity.Temp.AdjustHumidityRequest)) {
        return super.equals(obj);
      }
      humidity.Temp.AdjustHumidityRequest other = (humidity.Temp.AdjustHumidityRequest) obj;

      boolean result = true;
      result = result && getZoneId()
          .equals(other.getZoneId());
      result = result && (
          java.lang.Float.floatToIntBits(getHumidityAdjustment())
          == java.lang.Float.floatToIntBits(
              other.getHumidityAdjustment()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ZONE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getZoneId().hashCode();
      hash = (37 * hash) + HUMIDITY_ADJUSTMENT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHumidityAdjustment());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static humidity.Temp.AdjustHumidityRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.AdjustHumidityRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(humidity.Temp.AdjustHumidityRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code humidity.AdjustHumidityRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:humidity.AdjustHumidityRequest)
        humidity.Temp.AdjustHumidityRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return humidity.Temp.internal_static_humidity_AdjustHumidityRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return humidity.Temp.internal_static_humidity_AdjustHumidityRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                humidity.Temp.AdjustHumidityRequest.class, humidity.Temp.AdjustHumidityRequest.Builder.class);
      }

      // Construct using humidity.Temp.AdjustHumidityRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        zoneId_ = "";

        humidityAdjustment_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return humidity.Temp.internal_static_humidity_AdjustHumidityRequest_descriptor;
      }

      @java.lang.Override
      public humidity.Temp.AdjustHumidityRequest getDefaultInstanceForType() {
        return humidity.Temp.AdjustHumidityRequest.getDefaultInstance();
      }

      @java.lang.Override
      public humidity.Temp.AdjustHumidityRequest build() {
        humidity.Temp.AdjustHumidityRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public humidity.Temp.AdjustHumidityRequest buildPartial() {
        humidity.Temp.AdjustHumidityRequest result = new humidity.Temp.AdjustHumidityRequest(this);
        result.zoneId_ = zoneId_;
        result.humidityAdjustment_ = humidityAdjustment_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof humidity.Temp.AdjustHumidityRequest) {
          return mergeFrom((humidity.Temp.AdjustHumidityRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(humidity.Temp.AdjustHumidityRequest other) {
        if (other == humidity.Temp.AdjustHumidityRequest.getDefaultInstance()) return this;
        if (!other.getZoneId().isEmpty()) {
          zoneId_ = other.zoneId_;
          onChanged();
        }
        if (other.getHumidityAdjustment() != 0F) {
          setHumidityAdjustment(other.getHumidityAdjustment());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        humidity.Temp.AdjustHumidityRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (humidity.Temp.AdjustHumidityRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object zoneId_ = "";
      /**
       * <code>string zone_id = 1;</code>
       */
      public java.lang.String getZoneId() {
        java.lang.Object ref = zoneId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zoneId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getZoneIdBytes() {
        java.lang.Object ref = zoneId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zoneId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public Builder setZoneId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public Builder clearZoneId() {
        
        zoneId_ = getDefaultInstance().getZoneId();
        onChanged();
        return this;
      }
      /**
       * <code>string zone_id = 1;</code>
       */
      public Builder setZoneIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zoneId_ = value;
        onChanged();
        return this;
      }

      private float humidityAdjustment_ ;
      /**
       * <code>float humidity_adjustment = 2;</code>
       */
      public float getHumidityAdjustment() {
        return humidityAdjustment_;
      }
      /**
       * <code>float humidity_adjustment = 2;</code>
       */
      public Builder setHumidityAdjustment(float value) {
        
        humidityAdjustment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float humidity_adjustment = 2;</code>
       */
      public Builder clearHumidityAdjustment() {
        
        humidityAdjustment_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:humidity.AdjustHumidityRequest)
    }

    // @@protoc_insertion_point(class_scope:humidity.AdjustHumidityRequest)
    private static final humidity.Temp.AdjustHumidityRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new humidity.Temp.AdjustHumidityRequest();
    }

    public static humidity.Temp.AdjustHumidityRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdjustHumidityRequest>
        PARSER = new com.google.protobuf.AbstractParser<AdjustHumidityRequest>() {
      @java.lang.Override
      public AdjustHumidityRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdjustHumidityRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdjustHumidityRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdjustHumidityRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public humidity.Temp.AdjustHumidityRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdjustHumidityResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:humidity.AdjustHumidityResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float adjusted_humidity = 1;</code>
     */
    float getAdjustedHumidity();
  }
  /**
   * Protobuf type {@code humidity.AdjustHumidityResponse}
   */
  public  static final class AdjustHumidityResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:humidity.AdjustHumidityResponse)
      AdjustHumidityResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdjustHumidityResponse.newBuilder() to construct.
    private AdjustHumidityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdjustHumidityResponse() {
      adjustedHumidity_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdjustHumidityResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              adjustedHumidity_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return humidity.Temp.internal_static_humidity_AdjustHumidityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return humidity.Temp.internal_static_humidity_AdjustHumidityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              humidity.Temp.AdjustHumidityResponse.class, humidity.Temp.AdjustHumidityResponse.Builder.class);
    }

    public static final int ADJUSTED_HUMIDITY_FIELD_NUMBER = 1;
    private float adjustedHumidity_;
    /**
     * <code>float adjusted_humidity = 1;</code>
     */
    public float getAdjustedHumidity() {
      return adjustedHumidity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (adjustedHumidity_ != 0F) {
        output.writeFloat(1, adjustedHumidity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (adjustedHumidity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, adjustedHumidity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof humidity.Temp.AdjustHumidityResponse)) {
        return super.equals(obj);
      }
      humidity.Temp.AdjustHumidityResponse other = (humidity.Temp.AdjustHumidityResponse) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getAdjustedHumidity())
          == java.lang.Float.floatToIntBits(
              other.getAdjustedHumidity()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADJUSTED_HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAdjustedHumidity());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static humidity.Temp.AdjustHumidityResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static humidity.Temp.AdjustHumidityResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(humidity.Temp.AdjustHumidityResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code humidity.AdjustHumidityResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:humidity.AdjustHumidityResponse)
        humidity.Temp.AdjustHumidityResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return humidity.Temp.internal_static_humidity_AdjustHumidityResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return humidity.Temp.internal_static_humidity_AdjustHumidityResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                humidity.Temp.AdjustHumidityResponse.class, humidity.Temp.AdjustHumidityResponse.Builder.class);
      }

      // Construct using humidity.Temp.AdjustHumidityResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        adjustedHumidity_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return humidity.Temp.internal_static_humidity_AdjustHumidityResponse_descriptor;
      }

      @java.lang.Override
      public humidity.Temp.AdjustHumidityResponse getDefaultInstanceForType() {
        return humidity.Temp.AdjustHumidityResponse.getDefaultInstance();
      }

      @java.lang.Override
      public humidity.Temp.AdjustHumidityResponse build() {
        humidity.Temp.AdjustHumidityResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public humidity.Temp.AdjustHumidityResponse buildPartial() {
        humidity.Temp.AdjustHumidityResponse result = new humidity.Temp.AdjustHumidityResponse(this);
        result.adjustedHumidity_ = adjustedHumidity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof humidity.Temp.AdjustHumidityResponse) {
          return mergeFrom((humidity.Temp.AdjustHumidityResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(humidity.Temp.AdjustHumidityResponse other) {
        if (other == humidity.Temp.AdjustHumidityResponse.getDefaultInstance()) return this;
        if (other.getAdjustedHumidity() != 0F) {
          setAdjustedHumidity(other.getAdjustedHumidity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        humidity.Temp.AdjustHumidityResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (humidity.Temp.AdjustHumidityResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float adjustedHumidity_ ;
      /**
       * <code>float adjusted_humidity = 1;</code>
       */
      public float getAdjustedHumidity() {
        return adjustedHumidity_;
      }
      /**
       * <code>float adjusted_humidity = 1;</code>
       */
      public Builder setAdjustedHumidity(float value) {
        
        adjustedHumidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float adjusted_humidity = 1;</code>
       */
      public Builder clearAdjustedHumidity() {
        
        adjustedHumidity_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:humidity.AdjustHumidityResponse)
    }

    // @@protoc_insertion_point(class_scope:humidity.AdjustHumidityResponse)
    private static final humidity.Temp.AdjustHumidityResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new humidity.Temp.AdjustHumidityResponse();
    }

    public static humidity.Temp.AdjustHumidityResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdjustHumidityResponse>
        PARSER = new com.google.protobuf.AbstractParser<AdjustHumidityResponse>() {
      @java.lang.Override
      public AdjustHumidityResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdjustHumidityResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdjustHumidityResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdjustHumidityResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public humidity.Temp.AdjustHumidityResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_humidity_CurrentHumidityRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_humidity_CurrentHumidityRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_humidity_CurrentHumidityResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_humidity_CurrentHumidityResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_humidity_AdjustHumidityRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_humidity_AdjustHumidityRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_humidity_AdjustHumidityResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_humidity_AdjustHumidityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntemp.proto\022\010humidity\")\n\026CurrentHumidit" +
      "yRequest\022\017\n\007zone_id\030\001 \001(\t\"3\n\027CurrentHumi" +
      "dityResponse\022\030\n\020current_humidity\030\001 \001(\002\"E" +
      "\n\025AdjustHumidityRequest\022\017\n\007zone_id\030\001 \001(\t" +
      "\022\033\n\023humidity_adjustment\030\002 \001(\002\"3\n\026AdjustH" +
      "umidityResponse\022\031\n\021adjusted_humidity\030\001 \001" +
      "(\0022\311\001\n\017HumidityService\022]\n\022GetCurrentHumi" +
      "dity\022 .humidity.CurrentHumidityRequest\032!" +
      ".humidity.CurrentHumidityResponse\"\0000\001\022W\n" +
      "\016AdjustHumidity\022\037.humidity.AdjustHumidit" +
      "yRequest\032 .humidity.AdjustHumidityRespon" +
      "se\"\0000\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_humidity_CurrentHumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_humidity_CurrentHumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_humidity_CurrentHumidityRequest_descriptor,
        new java.lang.String[] { "ZoneId", });
    internal_static_humidity_CurrentHumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_humidity_CurrentHumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_humidity_CurrentHumidityResponse_descriptor,
        new java.lang.String[] { "CurrentHumidity", });
    internal_static_humidity_AdjustHumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_humidity_AdjustHumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_humidity_AdjustHumidityRequest_descriptor,
        new java.lang.String[] { "ZoneId", "HumidityAdjustment", });
    internal_static_humidity_AdjustHumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_humidity_AdjustHumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_humidity_AdjustHumidityResponse_descriptor,
        new java.lang.String[] { "AdjustedHumidity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
